//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Cotizacion
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class EntidadBDCotizacion : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto EntidadBDCotizacion usando la cadena de conexión encontrada en la sección 'EntidadBDCotizacion' del archivo de configuración de la aplicación.
        /// </summary>
        public EntidadBDCotizacion() : base("name=EntidadBDCotizacion", "EntidadBDCotizacion")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EntidadBDCotizacion.
        /// </summary>
        public EntidadBDCotizacion(string connectionString) : base(connectionString, "EntidadBDCotizacion")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EntidadBDCotizacion.
        /// </summary>
        public EntidadBDCotizacion(EntityConnection connection) : base(connection, "EntidadBDCotizacion")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Livianos> Livianos
        {
            get
            {
                if ((_Livianos == null))
                {
                    _Livianos = base.CreateObjectSet<Livianos>("Livianos");
                }
                return _Livianos;
            }
        }
        private ObjectSet<Livianos> _Livianos;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Livianos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToLivianos(Livianos livianos)
        {
            base.AddObject("Livianos", livianos);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDCotizacionModel", Name="Livianos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Livianos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Livianos.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        public static Livianos CreateLivianos(global::System.Int32 id)
        {
            Livianos livianos = new Livianos();
            livianos.Id = id;
            return livianos;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, true, "Codigo");
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Anno
        {
            get
            {
                return _Anno;
            }
            set
            {
                OnAnnoChanging(value);
                ReportPropertyChanging("Anno");
                _Anno = StructuralObject.SetValidValue(value, "Anno");
                ReportPropertyChanged("Anno");
                OnAnnoChanged();
            }
        }
        private Nullable<global::System.Int32> _Anno;
        partial void OnAnnoChanging(Nullable<global::System.Int32> value);
        partial void OnAnnoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, true, "Tipo");
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Marca
        {
            get
            {
                return _Marca;
            }
            set
            {
                OnMarcaChanging(value);
                ReportPropertyChanging("Marca");
                _Marca = StructuralObject.SetValidValue(value, true, "Marca");
                ReportPropertyChanged("Marca");
                OnMarcaChanged();
            }
        }
        private global::System.String _Marca;
        partial void OnMarcaChanging(global::System.String value);
        partial void OnMarcaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Modelo
        {
            get
            {
                return _Modelo;
            }
            set
            {
                OnModeloChanging(value);
                ReportPropertyChanging("Modelo");
                _Modelo = StructuralObject.SetValidValue(value, true, "Modelo");
                ReportPropertyChanged("Modelo");
                OnModeloChanged();
            }
        }
        private global::System.String _Modelo;
        partial void OnModeloChanging(global::System.String value);
        partial void OnModeloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Puertas
        {
            get
            {
                return _Puertas;
            }
            set
            {
                OnPuertasChanging(value);
                ReportPropertyChanging("Puertas");
                _Puertas = StructuralObject.SetValidValue(value, true, "Puertas");
                ReportPropertyChanged("Puertas");
                OnPuertasChanged();
            }
        }
        private global::System.String _Puertas;
        partial void OnPuertasChanging(global::System.String value);
        partial void OnPuertasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cilindros
        {
            get
            {
                return _Cilindros;
            }
            set
            {
                OnCilindrosChanging(value);
                ReportPropertyChanging("Cilindros");
                _Cilindros = StructuralObject.SetValidValue(value, true, "Cilindros");
                ReportPropertyChanged("Cilindros");
                OnCilindrosChanged();
            }
        }
        private global::System.String _Cilindros;
        partial void OnCilindrosChanging(global::System.String value);
        partial void OnCilindrosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Combustible
        {
            get
            {
                return _Combustible;
            }
            set
            {
                OnCombustibleChanging(value);
                ReportPropertyChanging("Combustible");
                _Combustible = StructuralObject.SetValidValue(value, true, "Combustible");
                ReportPropertyChanged("Combustible");
                OnCombustibleChanged();
            }
        }
        private global::System.String _Combustible;
        partial void OnCombustibleChanging(global::System.String value);
        partial void OnCombustibleChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Transmision
        {
            get
            {
                return _Transmision;
            }
            set
            {
                OnTransmisionChanging(value);
                ReportPropertyChanging("Transmision");
                _Transmision = StructuralObject.SetValidValue(value, true, "Transmision");
                ReportPropertyChanged("Transmision");
                OnTransmisionChanged();
            }
        }
        private global::System.String _Transmision;
        partial void OnTransmisionChanging(global::System.String value);
        partial void OnTransmisionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Equipo
        {
            get
            {
                return _Equipo;
            }
            set
            {
                OnEquipoChanging(value);
                ReportPropertyChanging("Equipo");
                _Equipo = StructuralObject.SetValidValue(value, true, "Equipo");
                ReportPropertyChanged("Equipo");
                OnEquipoChanged();
            }
        }
        private global::System.String _Equipo;
        partial void OnEquipoChanging(global::System.String value);
        partial void OnEquipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tasacion
        {
            get
            {
                return _Tasacion;
            }
            set
            {
                OnTasacionChanging(value);
                ReportPropertyChanging("Tasacion");
                _Tasacion = StructuralObject.SetValidValue(value, true, "Tasacion");
                ReportPropertyChanged("Tasacion");
                OnTasacionChanged();
            }
        }
        private global::System.String _Tasacion;
        partial void OnTasacionChanging(global::System.String value);
        partial void OnTasacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Permiso
        {
            get
            {
                return _Permiso;
            }
            set
            {
                OnPermisoChanging(value);
                ReportPropertyChanging("Permiso");
                _Permiso = StructuralObject.SetValidValue(value, true, "Permiso");
                ReportPropertyChanged("Permiso");
                OnPermisoChanged();
            }
        }
        private global::System.String _Permiso;
        partial void OnPermisoChanging(global::System.String value);
        partial void OnPermisoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    }

    #endregion

}
